### ISSUE TITLE
SSL error in self update part of topgrade

### ISSUE THREAD

**Issue by boetk** [r-darwish/topgrade#416] opened 2020-06-02 05:36 UTC
**What did you expect to happen?**
I have previously have topgrade and it have self updated, but instead it just gives me an SSL error.

**What actually happened?**
I run the topgrade script, and I get this error:
―― 07:30:13 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: ReqwestError: error sending request for url (https://api.github.com/repos/r-darwish/topgrade/releases/latest): error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269: (unable to get local issuer certificate)

**Additional details:**
- Which operating system or Linux distribution are you using?
Fedora KDE spin
- How did you install Topgrade?
I extracted this version: topgrade-v4.5.0-x86_64-unknown-linux-gnu.tar.gz
Running sudo ./topgrade
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
Running Dry-run doesn't show anything on self update

<details><pre>

2020-06-02T05:34:59.708Z DEBUG topgrade::config > Configuration at /home/mibn/.config/topgrade.toml
 2020-06-02T05:34:59.709Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: None, remote_topgrades: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None }
 2020-06-02T05:34:59.709Z DEBUG topgrade::utils  > Detected "/usr/bin/notify-send" as "notify-send"
 2020-06-02T05:34:59.709Z DEBUG topgrade         > Version: 4.5.0
 2020-06-02T05:34:59.709Z DEBUG topgrade         > OS: x86_64-unknown-linux-gnu
 2020-06-02T05:34:59.709Z DEBUG topgrade         > Args { inner: ["./topgrade", "-v"] }
 2020-06-02T05:34:59.709Z DEBUG topgrade         > Binary path: Ok("/opt/topgrade")
 2020-06-02T05:34:59.709Z DEBUG topgrade         > Self Update: true
 2020-06-02T05:34:59.709Z DEBUG topgrade::utils  > Cannot find "git"
 2020-06-02T05:34:59.709Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"

―― 07:34:59 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: ReqwestError: error sending request for url (https://api.github.com/repos/r-darwish/topgrade/releases/latest): error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269: (unable to get local issuer certificate)
 2020-06-02T05:34:59.815Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2020-06-02T05:34:59.815Z DEBUG topgrade::utils  > Cannot find "powershell"
 2020-06-02T05:34:59.815Z DEBUG topgrade::runner > Step "System update"

―― 07:34:59 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-06-02T05:34:59.816Z DEBUG topgrade::executor > Running "/usr/bin/sudo" "/usr/bin/dnf" "upgrade"
Last metadata expiration check: 0:08:57 ago on Tue 02 Jun 2020 07:26:04 CEST.
Dependencies resolved.
Nothing to do.
Complete!
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner   > Step "etc-update"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils    > Cannot find "etc-update"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner   > Step "brew"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils    > Cannot find "brew"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner   > Step "nix"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils    > Cannot find "nix"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner   > Step "home-manager"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils    > Cannot find "home-manager"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner   > Step "asdf"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils    > Cannot find "asdf"
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.doom.d does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.vim does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/nvim does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.zshrc does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.tmux does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/fish does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/openbox does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/bspwm does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/i3 does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::steps::git > /home/mibn/.config/sway does not exists
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "Git repositories"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "zr"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "antibody"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "antigen"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "zplug"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "zinit"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "oh-my-zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "zsh"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "fisher"
 2020-06-02T05:35:02.916Z DEBUG topgrade::utils      > Cannot find "fish"
 2020-06-02T05:35:02.916Z DEBUG topgrade::runner     > Step "tmux"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Path "/home/mibn/.tmux/plugins/tpm/bin/update_plugins" doesn't exist
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "TLDR"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "tldr"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "rustup"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "rustup"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "cargo"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "cargo-install-update"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "Flutter"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "flutter"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "Go"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "go"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "Emacs"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "emacs"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "opam"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "opam"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "vcpkg"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "vcpkg"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "pipx"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "pipx"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "stack"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "stack"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "myrepos"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "mr"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "pearl"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "pearl"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "jetpak"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "jetpack"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "vim"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "vim"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "Neovim"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "nvim"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "voom"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "voom"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "NPM"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "npm"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "yarn"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "yarn"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "composer"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "composer"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "apm"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "apm"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "gem"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Cannot find "gem"
 2020-06-02T05:35:02.917Z DEBUG topgrade::runner     > Step "Flatpak"
 2020-06-02T05:35:02.917Z DEBUG topgrade::utils      > Detected "/usr/bin/flatpak" as "flatpak"

―― 07:35:02 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
 2020-06-02T05:35:02.917Z DEBUG topgrade::executor   > Running "/usr/bin/flatpak" "update" "--user" "-y"
Looking for updates…
Nothing to do.
 2020-06-02T05:35:02.954Z DEBUG topgrade::executor   > Running "/usr/bin/flatpak" "update" "--system" "-y"
Looking for updates…
Nothing to do.
 2020-06-02T05:35:03.408Z DEBUG topgrade::runner     > Step "snap"
 2020-06-02T05:35:03.408Z DEBUG topgrade::utils      > Detected "/usr/bin/snap" as "snap"

―― 07:35:03 - snap ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-06-02T05:35:03.408Z DEBUG topgrade::executor   > Running "/usr/bin/sudo" "/usr/bin/snap" "refresh"
All snaps up to date.
 2020-06-02T05:35:04.227Z DEBUG topgrade::runner     > Step "pihole"
 2020-06-02T05:35:04.228Z DEBUG topgrade::utils      > Cannot find "pihole"
 2020-06-02T05:35:04.228Z DEBUG topgrade::runner     > Step "Firmware upgrades"
 2020-06-02T05:35:04.228Z DEBUG topgrade::utils      > Detected "/usr/bin/fwupdmgr" as "fwupdmgr"

―― 07:35:04 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
 2020-06-02T05:35:04.228Z DEBUG topgrade::executor   > Running "/usr/bin/fwupdmgr" "refresh"
Firmware metadata last refresh: 12 minutes ago. Use --force to refresh again.
 2020-06-02T05:35:04.272Z DEBUG topgrade::executor   > Running "/usr/bin/fwupdmgr" "get-updates"
• Thunderbolt Controller has no available firmware updates
• SAMSUNG MZVLW256HEHP-000L2 has no available firmware updates
• Touchpad has no available firmware updates
No updatable devices
 2020-06-02T05:35:04.298Z DEBUG topgrade::runner     > Step "Restarts"
 2020-06-02T05:35:04.298Z DEBUG topgrade::utils      > Cannot find "needrestart"
 2020-06-02T05:35:04.298Z DEBUG topgrade::runner     > Step "SDKMAN!"
 2020-06-02T05:35:04.298Z DEBUG topgrade::utils      > Detected "/usr/bin/bash" as "bash"
 2020-06-02T05:35:04.298Z DEBUG topgrade::utils      > Path "/home/mibn/.sdkman/bin/sdkman-init.sh" doesn't exist

―― 07:35:04 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
System update: OK
Flatpak: OK
snap: OK
Firmware upgrades: OK
</pre></details>

**Comment by r-darwish** [comment] 2020-06-03 06:44
Does `curl https://api.github.com` work on your system? Can you check if the `-musl` version of Topgrade causes any difference?

**Comment by boetk** [comment] 2020-06-03 15:17
Curl returns a JSON, which seems fine. Tell me if you want to know what it says.

You mean run `./topgrade -musl`? That doesn't seem to be a correct flag or am I misunderstanding you?

**Comment by r-darwish** [comment] 2020-06-03 17:01
No, I meant you should try this version:
https://github.com/r-darwish/topgrade/releases/download/v4.5.0/topgrade-v4.5.0-x86_64-unknown-linux-musl.tar.gz

**Comment by boetk** [comment] 2020-06-03 17:40
Ah, sure. Just get the same error as before.

**Comment by boetk** [comment] 2020-06-04 05:28
I have just tried to run version 4.4, which updates fine with no issues.
After version 4.4 updates to version 4.5 it has the same issue.

**Comment by SyedAmerGilani** [comment] 2020-06-04 06:29
I have the same issue. Also in Fedora(32).
4.4 updated fine to 4.5 and now 4.5 shows this error.
I saw ssl errors in the self update part before in old versions, but never minded and just manually updated.

**Comment by r-darwish** [comment] 2020-06-04 06:52
I think I have a guess about what's wrong. I'll try to submit a fix soon

**Comment by SyedAmerGilani** [comment] 2020-06-08 06:42
Still happening in version 4.6.0 (topgrade-v4.6.0-x86_64-unknown-linux-gnu.tar.gz)

`Self update error: ReqwestError: error sending request for url (https://api.github.com/repos/r-darwish/topgrade/releases/latest): error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269: (unable to get local issuer certificate)`

**Comment by r-darwish** [comment] 2020-06-09 18:23
I managed to reproduce it on a fedora VM. However, it even happens when running Rustup:

```
info: checking for self-updates
error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateEQfxry/release-stable.toml'
error: caused by: failed to make network request
error: caused by: https://static.rust-lang.org/rustup/release-stable.toml: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get l
ocal issuer certificate)
error: caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate)
```

So I'm closing this one as it doesn't seem like an issue specific to Topgrade.

**Comment by NotAFile** [comment] 2020-06-18 16:24
@r-darwish rustup fails in topgrade, however it succeeds if run independently. It must be related to some part of topgrade's exec environment.

**Comment by NotAFile** [comment] 2020-06-18 16:40
My guess would be that by modifying the environment variables or some other context, Topgrade breaks the process used to locate the system certificate store. It then falls back on the bundled store which contained the "AddTrust root" which expired on May 30, 2020, which is more or less when this issue showed up.

Redhat-based systems SSL configurations are slightly unusual because they store their certificate store in `/etc/pki/tls/certs/` instead of the `/etc/ssl/` used by the majority of other distributions.

**Comment by NotAFile** [comment] 2020-06-18 17:07
A diff of the env reveals the following entries are added when run with topgrade:

+SSL_CERT_DIR=/etc/ssl/certs
+SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

These appear to be set by `openssl-probe`, introduced to fix another ssl issue, https://github.com/r-darwish/topgrade/issues/161 which the self-update then leaks to the callees. I'll investigate futher before spamming more comments.

**Comment by r-darwish** [comment] 2020-06-18 19:11
@NotAFile thank you for investigating this issue.

**Comment by NotAFile** [comment] 2020-06-20 21:12
So this is is an issue with self-update, which hardcode overrides the ssl environment variables.

Luckily, it checks if those variables are set before overriding them, so you can just set these variables to the correct values as workaround. In my case, it worked with:

```bash
SSL_CERT_DIR=/etc/pki/tls/certs/ SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt topgrade
```

**Comment by r-darwish** [comment] 2020-06-21 12:28
I used to manage to reproduce this issue on Fedora but now it doesn't reproduce for some reason. I actually don't use openssl-probe at the moment. I can try to call it on Linux and see if it helps.

**Comment by r-darwish** [comment] 2020-08-01 13:12
fixed

**Closed by r-darwish** 2020-08-01 13:12 UTC
Labels: needs more information
