### ISSUE TITLE
Having some permission problems (for a while) with Go

### ISSUE THREAD

**Issue by msmafra** [r-darwish/topgrade#627] opened 2021-02-11 19:46 UTC
**What did you expect to happen?**
Go packages/files to get updated

**What actually happened?**

```
―― 16:43:05 - Go ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
go get cmd/internal/objfile: copying /home/marcelo/.cache/go-build/99/99e321ec8cc96c8b429d9531709c606c4644295334fd2b950bc28224fb50bb35-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/objfile.a: permission denied
go get cmd/asm/internal/lex: copying /home/marcelo/.cache/go-build/31/311ccba71286fa2ebe8bedb1547a281f9782c4a78cc52cdbc4f31037647449f2-d: open /usr/lib/golang/pkg/linux_amd64/cmd/asm/internal/lex.a: permission denied
go get cmd/internal/obj: copying /home/marcelo/.cache/go-build/ff/ff5a337d8f3c263945a7afb2cce4aab528d3b1388417445601110be3d820b05b-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/obj.a: permission denied
go get cmd/go/internal/work: copying /home/marcelo/.cache/go-build/84/84d4fc5c69eb8e6a454abc9bed7c6e9bedf3e9d2f7fe70070932f61073adcf78-d: open /usr/lib/golang/pkg/linux_amd64/cmd/go/internal/work.a: permission denied

Retry? (y)es/(N)o/(s)hell
```

**Additional details:**
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?
`cargo install topgrade`

Run `topgrade --dry-run` to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.
I don't know if it's correct:
```
―― 16:44:03 - Go ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/go get -u all in /home/marcelo/go

―― 16:44:03 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Go: OK

```

<details><pre>
❯ topgrade -v --cleanup --yes --only go
 2021-02-11T19:45:33.626Z DEBUG topgrade::config > Configuration at /home/marcelo/.config/topgrade.toml
 2021-02-11T19:45:33.626Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None }), linux: Some(Linux { yay_arguments: None, trizen_arguments: None, dnf_arguments: None, enable_tlmgr: None, redhat_distro_sync: Some(true), emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None }), vagrant: None }
 2021-02-11T19:45:33.626Z DEBUG topgrade::utils  > Detected "/usr/bin/notify-send" as "notify-send"
 2021-02-11T19:45:33.626Z DEBUG topgrade         > Version: 6.4.0
 2021-02-11T19:45:33.626Z DEBUG topgrade         > OS: x86_64-unknown-linux-gnu
 2021-02-11T19:45:33.626Z DEBUG topgrade         > Args { inner: ["topgrade", "-v", "--cleanup", "--yes", "--only", "go"] }
 2021-02-11T19:45:33.626Z DEBUG topgrade         > Binary path: Ok("/home/marcelo/.cargo/bin/topgrade")
 2021-02-11T19:45:33.626Z DEBUG topgrade         > Self Update: false
 2021-02-11T19:45:33.626Z DEBUG topgrade::utils  > Detected "/usr/bin/git" as "git"
 2021-02-11T19:45:33.626Z DEBUG topgrade::utils  > Detected "/usr/local/bin/doas" as "doas"
 2021-02-11T19:45:33.626Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2021-02-11T19:45:33.626Z DEBUG topgrade::utils  > Cannot find "powershell"
 2021-02-11T19:45:33.627Z DEBUG topgrade::utils  > Path "/home/marcelo/.config/emacs" doesn't exist
 2021-02-11T19:45:33.627Z DEBUG topgrade::utils  > Path "/home/marcelo/.emacs.d" doesn't exist
 2021-02-11T19:45:33.627Z DEBUG topgrade::steps::git > /home/marcelo/.zshrc is a file. Checking /home/marcelo
 2021-02-11T19:45:33.627Z DEBUG topgrade::steps::git > Checking if /home/marcelo is a git repository
 2021-02-11T19:45:33.629Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(32768)), stdout: "", stderr: "fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n" }
 2021-02-11T19:45:33.629Z DEBUG topgrade::steps::git > Checking if /home/marcelo/.config/fish is a git repository
 2021-02-11T19:45:33.631Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(32768)), stdout: "", stderr: "fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n" }
 2021-02-11T19:45:33.631Z DEBUG topgrade::steps::git > Checking if /home/marcelo/.config/openbox is a git repository
 2021-02-11T19:45:33.632Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(32768)), stdout: "", stderr: "fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n" }
 2021-02-11T19:45:33.632Z DEBUG topgrade::steps::git > /home/marcelo/.config/bspwm does not exists
 2021-02-11T19:45:33.632Z DEBUG topgrade::steps::git > Checking if /home/marcelo/.config/i3 is a git repository
 2021-02-11T19:45:33.635Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(32768)), stdout: "", stderr: "fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n" }
 2021-02-11T19:45:33.635Z DEBUG topgrade::steps::git > /home/marcelo/.config/sway does not exists
 2021-02-11T19:45:33.635Z DEBUG topgrade::runner     > Step "Go"
 2021-02-11T19:45:33.635Z DEBUG topgrade::utils      > Detected "/usr/bin/go" as "go"
 2021-02-11T19:45:33.635Z DEBUG topgrade::utils      > Path "/home/marcelo/go" exists

―― 16:45:33 - Go ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2021-02-11T19:45:33.640Z DEBUG topgrade::executor   > Running "/usr/bin/go" "get" "-u" "all"
go get cmd/internal/objfile: copying /home/marcelo/.cache/go-build/99/99e321ec8cc96c8b429d9531709c606c4644295334fd2b950bc28224fb50bb35-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/objfile.a: permission denied
go get cmd/asm/internal/lex: copying /home/marcelo/.cache/go-build/31/311ccba71286fa2ebe8bedb1547a281f9782c4a78cc52cdbc4f31037647449f2-d: open /usr/lib/golang/pkg/linux_amd64/cmd/asm/internal/lex.a: permission denied
go get cmd/internal/obj: copying /home/marcelo/.cache/go-build/ff/ff5a337d8f3c263945a7afb2cce4aab528d3b1388417445601110be3d820b05b-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/obj.a: permission denied
go get cmd/go/internal/work: copying /home/marcelo/.cache/go-build/84/84d4fc5c69eb8e6a454abc9bed7c6e9bedf3e9d2f7fe70070932f61073adcf78-d: open /usr/lib/golang/pkg/linux_amd64/cmd/go/internal/work.a: permission denied
 2021-02-11T19:45:34.921Z DEBUG topgrade::runner     > Step "Go" failed: exit code: 1
 2021-02-11T19:45:34.921Z DEBUG topgrade::terminal   > Desktop notification: Go failed

Retry? (y)es/(N)o/(s)hell

</pre></details>

**Comment by r-darwish** [comment] 2021-02-11 21:22
I don't know much about Go. @adamtabrams maybe you have an idea?

**Comment by adamtabrams** [comment] 2021-02-11 21:34
It looks like the user may not have read permissions for some of the files. The command seems to follow the prescribed way to update packages in the GOPATH. But it's hard to say if this is actually an error on caused by topgrade or by the packages in the GOPATH. From my understanding, Go has been shifting away from using GOPATH in favor of the go mod system. I personally use the go mod system, and don't have much experience with troubleshooting GOPATH issues.

@msmafra when you run `cd /home/marcelo/go` and then `/usr/bin/go get -u all` do you get the same errors that you got when `topgrade --only go`?

**Comment by msmafra** [comment] 2021-02-12 14:22
@adamtabrams hey!
Here it is:

```
❯ cd /home/marcelo/go
❯ ~/go ❯
❯ /usr/bin/go get -u all
go get cmd/internal/objfile: copying /home/marcelo/.cache/go-build/99/99e321ec8cc96c8b429d9531709c606c4644295334fd2b950bc28224fb50bb35-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/objfile.a: permission denied
go get cmd/internal/obj: copying /home/marcelo/.cache/go-build/ff/ff5a337d8f3c263945a7afb2cce4aab528d3b1388417445601110be3d820b05b-d: open /usr/lib/golang/pkg/linux_amd64/cmd/internal/obj.a: permission denied
go get cmd/asm/internal/lex: copying /home/marcelo/.cache/go-build/31/311ccba71286fa2ebe8bedb1547a281f9782c4a78cc52cdbc4f31037647449f2-d: open /usr/lib/golang/pkg/linux_amd64/cmd/asm/internal/lex.a: permission denied
go get cmd/go/internal/work: copying /home/marcelo/.cache/go-build/84/84d4fc5c69eb8e6a454abc9bed7c6e9bedf3e9d2f7fe70070932f61073adcf78-d: open /usr/lib/golang/pkg/linux_amd64/cmd/go/internal/work.a: permission denied
❯ ~/go ❯
❯ doas /usr/bin/go get -u all
```
Those message have been shown for a while (many version), when it bothered me I used to _doas cp_ the line that was. Not just Go would have problems some times, but also RubyGems would issue errors, which coincidentally happened today. I
Shamefully I am not sure why I have Go. I am almost certain that is because of Restic, that I was about to test some random modification months and months back and ended up not testing it to not mess with my backups nor have to make a copy of my backups to mess with them.

```
―― 11:19:39 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2021-02-12T14:19:39.916Z DEBUG topgrade::steps::generic > Detected rbenv. Avoiding --user-install
 2021-02-12T14:19:39.916Z DEBUG topgrade::executor       > Running "/usr/bin/gem" "update" "--user-install"
Updating installed gems
Updating net-pop
Building native extensions. This could take a while...
ERROR:  Error installing net-pop:
	ERROR: Failed to build gem native extension.

    current directory: /home/marcelo/.gem/ruby/gems/digest-3.0.0/ext/digest
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20210212-258877-h4xn5d.rb extconf.rb
creating Makefile

current directory: /home/marcelo/.gem/ruby/gems/digest-3.0.0/ext/digest
make "DESTDIR=" clean
rm -f 
rm -f digest.so  *.o  *.bak mkmf.log .*.time

current directory: /home/marcelo/.gem/ruby/gems/digest-3.0.0/ext/digest
make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fPIC -m64 -o digest.o -c digest.c
rm -f digest.so
gcc -shared -o digest.so digest.o -L. -L/usr/lib64 -L. -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -m64  -lruby  -lm   -lc

current directory: /home/marcelo/.gem/ruby/gems/digest-3.0.0/ext/digest
make "DESTDIR=" install
/usr/bin/mkdir -p . ./.gem.20210212-258877-5ctn72
exit > .sitearchdir.time
/usr/bin/install -c -m 0755 digest.so ./.gem.20210212-258877-5ctn72
/usr/bin/mkdir -p . /usr/include/ruby
exit > .rubyhdrdir.-.ruby.time
/usr/bin/install -c -m 644 ./digest.h /usr/include/ruby
/usr/bin/install: não foi possível remover '/usr/include/ruby/digest.h': Permissão negada
make: *** [Makefile:204: /usr/include/ruby/digest.h] Erro 1

make install failed, exit code 2

Gem files will remain installed in /home/marcelo/.gem/ruby/gems/digest-3.0.0 for inspection.
Results logged to /home/marcelo/.gem/ruby/extensions/x86_64-linux/2.7.0/digest-3.0.0/gem_make.out
Gems updated: digest
```

**Comment by msmafra** [comment] 2021-02-12 15:40
The gems permission problems I changed the to 777 (doas chmod 777 /usr/include/ruby/), ran the command (/usr/bin/gem update -V --user-install) and restored the permissions (doas chmod 755 /usr/include/ruby/) to work. Most likely a temporary solution.

**Comment by r-darwish** [comment] 2021-02-21 07:44
It doesn't seem like an issue with Topgrade, so I'm closing this one.

**Closed by r-darwish** 2021-02-21 07:44 UTC
